codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  round: down
  range: '60...100'
  status:
    project:
      default:
        target: 70%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        if_ci_failed: error
    changes: yes