name: test

on:
  push:
    branches:
    tags:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 1.37.1
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go test -race -timeout=60s -v -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt